// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "xxxxxxx",
    "aws_cognito_identity_pool_id": "xxxxxxx",
    "aws_cognito_region": "xxxxxxx",
    "aws_user_pools_id": "xxxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxx",
    "oauth": {},
    "aws_user_files_s3_bucket": "xxxxxxx",
    "aws_user_files_s3_bucket_region": "xxxxxxx",
};


export default awsmobile;
