export const CHECK_PERMISSIONS = 'CHECK_PERMISSIONS'
export const ASK_PERMISSION = 'ASK_PERMISSION'
export const PERMISSIONS_UPDATED = 'PERMISSIONS_UPDATED'

export const SET_GEOFENCE = 'SET_GEOFENCE'

export const SET_SHOW_INTRO = 'SET_SHOW_INTRO'

export const GEOFENCE_TRIGGERED = 'GEOFENCE_TRIGGERED'
export const GEOFENCE_TASK = 'GEOFENCE_TASK'

export const BACKGROUND_LOCATION_TASK = 'BACKGROUND_LOCATION_TASK'
export const LOCATION_UPDATED = 'LOCATION_UPDATED'

export const START_TRACKING_LOCATION = 'START_TRACKING_LOCATION'
export const STOP_TRACKING_LOCATION = 'STOP_TRACKING_LOCATION'

export const DELETE_TRIPS = 'DELETE_TRIPS'

export const SUBMIT_REPORT = 'SUBMIT_REPORT'
export const SUBMIT_REPORT_PENDING = 'SUBMIT_REPORT_PENDING'
export const SUBMIT_REPORT_SUCCESS = 'SUBMIT_REPORT_SUCCESS'
export const SUBMIT_REPORT_FAILED = 'SUBMIT_REPORT_FAILED'